on: [push]
name: push_to_acr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push image with SHA and latest tags'
        run: |
          docker build -f Dockerfile.bun -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs-docker:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs-docker:latest .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs-docker:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs-docker:latest
