name: Build and deploy Node.js app to Azure Web App - front-pybox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # This installs the latest version of Bun

      - name: Install dependencies with Bun
        run: |
          bun install  

      - name: Build the app with Bun
        run: |
          bun run build  

      - name: List files before zipping
        run: ls -la

      - name: Zip artifact for deployment
        run: zip next.zip ./* .next -qr

      - name: List files after zipping
        run: ls -la

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: next.zip  # ✅ poprawiona nazwa pliku

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files after download
        run: ls -la

      - name: Unzip artifact for deployment
        run: unzip next.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'front-pybox'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9912E5A2DD174086A71EE3262D11DD30 }}
